name: Build and deploy data

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AEMET_API_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ENDPOINT_URL:
        required: true
      DATA_BUCKET:
        required: true
  schedule:
    - cron: "30 1,7,13,19 * * *"
      timezone: Europe/Madrid

permissions:
  packages: read

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Build data
        env:
          AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
        run: cielo build data --output /tmp/cielo-data

      - name: Deploy data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          DATA_BUCKET: ${{ secrets.DATA_BUCKET }}
        run: >-
          cielo deploy data
          --input /tmp/cielo-data
          --bucket "$DATA_BUCKET"
          --endpoint "$AWS_ENDPOINT_URL"
          --region auto
